# IMPORTANT NOTE: This was generated by Cursor to print out information about the users table.
# Especially when I was first developing the application, I needed to see if changes were registering
# appropriately in the database.

#!/usr/bin/env python3

import sqlite3
import json
from datetime import datetime

def inspect_users(db_path="backend/promptly.db"):
    """Inspect the contents of the users table"""
    try:
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()
        
        print("=" * 60)
        print("USERS TABLE INSPECTION")
        print("=" * 60)
        print()
        
        # Get column names for users table
        cursor.execute("PRAGMA table_info(users)")
        user_columns = [col[1] for col in cursor.fetchall()]
        print(f"Columns: {', '.join(user_columns)}")
        print()
        
        # Inspect users table and print out all data about it
        print("USERS:")
        print("-" * 60)
        cursor.execute("SELECT * FROM users")
        users = cursor.fetchall()
        
        if users:
            print(f"Total users: {len(users)}")
            print()
            for idx, user in enumerate(users):
                print(f"User #{idx + 1}:")
                for i, col_name in enumerate(user_columns):
                    value = user[i]
                    if col_name == "conversation_ids" and value:
                        try:
                            # Try to parse as JSON if it's stored that way
                            conv_ids = json.loads(value) if isinstance(value, str) else value
                            if isinstance(conv_ids, list):
                                print(f"  {col_name}: {len(conv_ids)} conversation(s) - {conv_ids}")
                            else:
                                print(f"  {col_name}: {value}")
                        except:
                            print(f"  {col_name}: {value}")
                    elif col_name in ["created_at", "last_login"]:
                        print(f"  {col_name}: {value}")
                    else:
                        print(f"  {col_name}: {value}")
                print("-" * 60)
        else:
            print("No users found")
        
        conn.close()
        
    except sqlite3.Error as e:
        print(f"Database error: {e}")
    except FileNotFoundError:
        print(f"Database file not found: {db_path}")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    inspect_users()

