# IMPORTANT NOTE: This was generated by Cursor to test the connection to Open AI's API, I had cursor make this when I was struggling to understand why sending a message suddenly broke.
#!/usr/bin/env python3
"""
Simple script to test OpenAI API connectivity and configuration.
Run this to debug OpenAI API issues.
"""

import sys
import os
from pathlib import Path

# Add backend directory to path
backend_dir = Path(__file__).parent / "backend"
sys.path.insert(0, str(backend_dir))

from config import Config
from ai_service import AIService

def test_openai():
    print("=" * 60)
    print("OpenAI API Test Script")
    print("=" * 60)
    print()
    
    # Check API key
    print("1. Checking API Key Configuration...")
    api_key = Config.OPENAI_API_KEY
    if not api_key or api_key == "your-api-key-here":
        print("   ❌ ERROR: OpenAI API key not configured!")
        print("   Please set your API key in one of these ways:")
        print("   1. Edit backend/api_key.py")
        print("   2. Set environment variable: export OPENAI_API_KEY='your-key-here'")
        print("   3. Create backend/.env file with: OPENAI_API_KEY=your-key-here")
        return False
    else:
        print(f"   ✓ API key is set (length: {len(api_key)} characters)")
        print(f"   ✓ API key starts with: {api_key[:7]}...")
    
    print()
    print("2. Initializing AI Service...")
    try:
        ai_service = AIService(api_key)
        print(f"   ✓ AI Service initialized")
        print(f"   ✓ Response model: {ai_service.response_model}")
        print(f"   ✓ Feedback model: {ai_service.feedback_model}")
    except Exception as e:
        print(f"   ❌ ERROR: Failed to initialize AI Service: {e}")
        return False
    
    print()
    print("3. Testing simple API call (non-streaming)...")
    try:
        test_messages = [
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": "Say 'Hello, API test successful!' and nothing else."}
        ]
        
        print(f"   Calling OpenAI API with model: {ai_service.response_model}")
        response = ai_service.client.chat.completions.create(
            model=ai_service.response_model,
            messages=test_messages,
            max_tokens=50
        )
        
        if response.choices and response.choices[0].message:
            content = response.choices[0].message.content
            print(f"   ✓ API call successful!")
            print(f"   ✓ Response: {content}")
            
            if hasattr(response, 'usage') and response.usage:
                print(f"   ✓ Token usage:")
                print(f"     - Prompt tokens: {response.usage.prompt_tokens}")
                print(f"     - Completion tokens: {response.usage.completion_tokens}")
                print(f"     - Total tokens: {response.usage.total_tokens}")
            
            return True
        else:
            print("   ❌ ERROR: Empty response from OpenAI")
            return False
            
    except Exception as e:
        error_type = type(e).__name__
        error_msg = str(e)
        print(f"   ❌ ERROR: API call failed ({error_type})")
        print(f"   Error message: {error_msg}")
        
        # Provide helpful suggestions
        if "rate limit" in error_msg.lower():
            print()
            print("   💡 Suggestion: Rate limit exceeded. Wait a moment and try again.")
        elif "invalid" in error_msg.lower() or "authentication" in error_msg.lower():
            print()
            print("   💡 Suggestion: API key may be invalid. Check your API key.")
        elif "connection" in error_msg.lower() or "network" in error_msg.lower():
            print()
            print("   💡 Suggestion: Network connection issue. Check your internet.")
        
        import traceback
        print()
        print("   Full traceback:")
        traceback.print_exc()
        return False
    
    print()
    print("4. Testing streaming API call...")
    try:
        test_messages = [
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": "Count from 1 to 5, one number per line."}
        ]
        
        print(f"   Calling OpenAI API with streaming: {ai_service.response_model}")
        stream = ai_service.client.chat.completions.create(
            model=ai_service.response_model,
            messages=test_messages,
            stream=True,
            max_tokens=50
        )
        
        full_response = ""
        chunk_count = 0
        for chunk in stream:
            if chunk.choices and len(chunk.choices) > 0:
                delta = chunk.choices[0].delta
                if delta and delta.content:
                    full_response += delta.content
                    chunk_count += 1
        
        print(f"   ✓ Streaming API call successful!")
        print(f"   ✓ Received {chunk_count} chunks")
        print(f"   ✓ Full response: {full_response}")
        return True
        
    except Exception as e:
        error_type = type(e).__name__
        error_msg = str(e)
        print(f"   ❌ ERROR: Streaming API call failed ({error_type})")
        print(f"   Error message: {error_msg}")
        
        import traceback
        print()
        print("   Full traceback:")
        traceback.print_exc()
        return False

if __name__ == '__main__':
    success = test_openai()
    print()
    print("=" * 60)
    if success:
        print("✓ All tests passed! OpenAI API is working correctly.")
    else:
        print("✗ Some tests failed. Check the errors above.")
    print("=" * 60)
    sys.exit(0 if success else 1)

