# IMPORTANT NOTE: This was generated by Cursor, it contains the configuration and important
# variables for the backend.
import os
from dotenv import load_dotenv

# Try to load from environment first, then fall back to api_key.py
load_dotenv()

try:
    from api_key import OPENAI_API_KEY as API_KEY_FROM_FILE
except ImportError:
    API_KEY_FROM_FILE = None

class Config:
    # Use environment variable first, then file, then None
    OPENAI_API_KEY = os.getenv('OPENAI_API_KEY') or API_KEY_FROM_FILE
    
    # Database URL - Render provides DATABASE_URL for PostgreSQL
    # For local dev, use SQLite if DATABASE_URL is not set
    DATABASE_URL = os.getenv('DATABASE_URL', 'sqlite:///promptly.db')
    
    SECRET_KEY = os.getenv('SECRET_KEY', 'dev-secret-key-change-in-production')
    
    AUTH0_DOMAIN = os.getenv('AUTH0_DOMAIN', '')
    AUTH0_API_AUDIENCE = os.getenv('AUTH0_API_AUDIENCE', '')
    AUTH0_ALGORITHMS = os.getenv('AUTH0_ALGORITHMS', 'RS256')
    AUTH0_ISSUER = f"https://{os.getenv('AUTH0_DOMAIN', '')}/" if os.getenv('AUTH0_DOMAIN') else ''
    
    # Production settings
    ENVIRONMENT = os.getenv('ENVIRONMENT', 'development')
    DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'
    
    # CORS settings - allow frontend URL in production
    FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')