// IMPORTANT NOTE: This and the associated css file were generated by Cursor with a lot of back-and-forth - I have very little
//experience with frontend development, especially using React, so it could help me implement
//things that I was more familiar with in this language.
import React from "react";
import { AlertTriangle, X } from "lucide-react";
import "./ConfirmationModal.css";

const ConfirmationModal = ({
  isOpen,
  title = "Confirm Action",
  message,
  confirmText = "Confirm",
  cancelText = "Cancel",
  onConfirm,
  onCancel,
  confirmButtonColor = "#d32f2f", // Default red for delete actions
}) => {
  // this is just a basic popup that comes up to confirm when a user wants to delete a conversation
  if (!isOpen) return null;

  const handleOverlayClick = (e) => {
    if (e.target === e.currentTarget) {
      onCancel();
    }
  };

  return (
    <div
      className="confirmation-modal-overlay"
      onClick={handleOverlayClick}
      data-testid="confirmation-modal-overlay"
    >
      <div
        className="confirmation-modal-content"
        onClick={(e) => e.stopPropagation()}
        data-testid="confirmation-modal-content"
      >
        <div className="confirmation-modal-header">
          <div className="confirmation-modal-title">
            <AlertTriangle size={24} className="confirmation-icon" />
            <h2>{title}</h2>
          </div>
          <button
            className="confirmation-modal-close"
            onClick={onCancel}
            title="Close"
          >
            <X size={18} />
          </button>
        </div>

        <div className="confirmation-modal-body">
          <p className="confirmation-message">{message}</p>
        </div>

        <div className="confirmation-modal-footer">
          <button
            className="confirmation-button cancel-button"
            onClick={onCancel}
          >
            {cancelText}
          </button>
          <button
            className="confirmation-button confirm-button"
            onClick={onConfirm}
            style={{ backgroundColor: confirmButtonColor }}
          >
            {confirmText}
          </button>
        </div>
      </div>
    </div>
  );
};

export default ConfirmationModal;
