// IMPORTANT NOTE: This and the associated css file were generated by Cursor with a lot of back-and-forth - I have very little
//experience with frontend development, especially using React, so it could help me implement
//things that I was more familiar with in this language.
import React from "react";
import { Plus, MessageSquare, Clock } from "lucide-react";
import "./ConversationList.css";

const ConversationList = ({
  conversations,
  currentConversationId,
  onSelectConversation,
  onCreateNew,
  loading = false,
  isNewConversation = false,
}) => {
  const formatDate = (dateString) => {
    if (!dateString) return "Unknown";
    const date = new Date(dateString);
    const now = new Date();

    // Calculate difference in days (not absolute, to handle timezone issues)
    const diffTime = now - date;
    const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));

    // formatting to make the days references look normal
    if (diffDays < 0) return "Today"; // Handle negative days (timezone issues)
    if (diffDays === 0) return "Today";
    if (diffDays === 1) return "Yesterday";
    if (diffDays <= 7) return `${diffDays} days ago`;
    return date.toLocaleDateString();
  };

  return (
    <div className="conversation-list">
      <div className="conversation-header">
        <h2>Conversations</h2>
        <div className="new-conversation-btn-wrapper">
          <button
            className={`new-conversation-btn ${
              isNewConversation ? "disabled" : ""
            }`}
            onClick={onCreateNew}
            title={isNewConversation ? undefined : "Start new conversation"}
            disabled={isNewConversation}
          >
            <Plus size={20} />
          </button>
          {isNewConversation && (
            <div className="tooltip">
              You have a new conversation open in the main window.
            </div>
          )}
        </div>
      </div>

      <div className="conversation-items">
        {loading ? (
          <div className="empty-state">
            <MessageSquare size={48} className="empty-icon" />
            <p>Loading conversations...</p>
          </div>
        ) : conversations.length === 0 ? (
          <div className="empty-state">
            <MessageSquare size={48} className="empty-icon" />
            <p>No conversations yet</p>
            <p>Start your first conversation in the main window!</p>
          </div>
        ) : (
          conversations.map((conversation) => (
            <div
              key={conversation.conversation_id}
              className={`conversation-item ${
                currentConversationId === conversation.conversation_id
                  ? "active"
                  : ""
              }`}
              onClick={() => onSelectConversation(conversation.conversation_id)}
            >
              <div className="conversation-content">
                <h3 className="conversation-title">
                  {conversation.title || "New Conversation"}
                </h3>
                <div className="conversation-meta">
                  <span className="message-count">
                    {conversation.message_count || 0}{" "}
                    {conversation.message_count === 1 ? "message" : "messages"}
                  </span>
                  <span className="conversation-date">
                    <Clock size={12} />
                    {formatDate(conversation.updated_at)}
                  </span>
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
};

export default ConversationList;
