// IMPORTANT NOTE: This and the associated css file were generated by Cursor with a lot of back-and-forth - I have very little
//experience with frontend development, especially using React, so it could help me implement
//things that I was more familiar with in this language.
import React, { useState, useEffect, useRef } from "react";
import { createPortal } from "react-dom";
import { Plus, MessageSquare, Clock, Trash2 } from "lucide-react";
import "./ConversationList.css";

const ConversationList = ({
  conversations,
  currentConversationId,
  onSelectConversation,
  onCreateNew,
  onDeleteConversation,
  loading = false,
  isNewConversation = false,
  isStreaming = false,
}) => {
  const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });
  const [showTooltip, setShowTooltip] = useState(false);
  const tooltipTimeoutRef = useRef(null);
  const conversationItemsRef = useRef(null);

  // when the user clicks on something in the conversation list when a response is loading, displays tooltip
  const handleClickShowTooltip = (e) => {
    setMousePosition({ x: e.clientX, y: e.clientY });
    setShowTooltip(true);

    // Clear existing timeout after 2000ms which is 2 sec
    if (tooltipTimeoutRef.current) {
      clearTimeout(tooltipTimeoutRef.current);
    }

    // Hide tooltip after 2 seconds
    tooltipTimeoutRef.current = setTimeout(() => {
      setShowTooltip(false);
    }, 2000);
  };

  // Track mouse position to make tooltip follow cursor after it appears
  useEffect(() => {
    if (!showTooltip) return;

    const handleMouseMove = (e) => {
      setMousePosition({ x: e.clientX, y: e.clientY });
    };

    document.addEventListener("mousemove", handleMouseMove);

    return () => {
      document.removeEventListener("mousemove", handleMouseMove);
    };
  }, [showTooltip]);

  // Cleanup timeout on unmount
  useEffect(() => {
    return () => {
      if (tooltipTimeoutRef.current) {
        clearTimeout(tooltipTimeoutRef.current);
      }
    };
  }, []);

  const formatDate = (dateString) => {
    if (!dateString) return "Unknown";
    const date = new Date(dateString);
    const now = new Date();

    // Calculate difference in days (not absolute, to handle timezone issues)
    const diffTime = now - date;
    const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));

    // formatting to make the days references look normal
    if (diffDays < 0) return "Today"; // this handles negative days (timezone issues) which was an issue i was having in indonesia
    if (diffDays === 0) return "Today";
    if (diffDays === 1) return "Yesterday";
    if (diffDays <= 7) return `${diffDays} days ago`;
    return date.toLocaleDateString();
  };

  // Handle plus button click
  const handleCreateNew = (e) => {
    const isDisabled = isNewConversation || isStreaming;
    if (isDisabled) {
      handleClickShowTooltip(e);
      return; // Prevent action, show tooltip
    }
    onCreateNew();
  };

  // Handle conversation item click
  const handleSelectConversation = (conversationId, e) => {
    if (isStreaming) {
      e.stopPropagation(); // Prevents users from clicking the delete button
      handleClickShowTooltip(e);
      return; // Prevent action, show tooltip
    }
    onSelectConversation(conversationId);
  };

  // Handle click on conversation items container
  const handleConversationItemsClick = (e) => {
    if (isStreaming) {
      handleClickShowTooltip(e);
    }
  };

  return (
    <div className="conversation-list">
      <div className="conversation-header">
        <h2>Conversations</h2>
        <div className="new-conversation-btn-wrapper">
          <button
            className={`new-conversation-btn ${
              isNewConversation || isStreaming ? "disabled" : ""
            }`}
            onClick={handleCreateNew}
            title={
              isNewConversation
                ? undefined
                : isStreaming
                ? undefined
                : "Start new conversation"
            }
            disabled={isNewConversation || isStreaming}
          >
            <Plus size={20} />
          </button>
          {isNewConversation && (
            <div className="tooltip">
              You have a new conversation open in the main window.
            </div>
          )}
        </div>
      </div>
      {/* List of conversations, either loading, empty, or displaying a list of conversations */}
      <div
        className="conversation-items"
        ref={conversationItemsRef}
        onClick={isStreaming ? handleConversationItemsClick : undefined}
      >
        {loading ? (
          <div className="empty-state">
            <MessageSquare size={48} className="empty-icon" />
            <p>Loading conversations...</p>
          </div>
        ) : conversations.length === 0 ? (
          <div className="empty-state">
            <MessageSquare size={48} className="empty-icon" />
            <p>No conversations yet</p>
            <p>Start your first conversation in the main window!</p>
          </div>
        ) : (
          conversations.map((conversation) => (
            // Deactivates the conversation item if a response is loading
            <div
              key={conversation.conversation_id}
              className={`conversation-item ${
                currentConversationId === conversation.conversation_id
                  ? "active"
                  : ""
              } ${isStreaming ? "streaming-disabled" : ""}`}
              onClick={(e) =>
                handleSelectConversation(conversation.conversation_id, e)
              }
            >
              <div className="conversation-content">
                <h3 className="conversation-title">
                  {conversation.title || "New Conversation"}
                </h3>
                <div className="conversation-meta">
                  <span className="message-count">
                    {conversation.message_count || 0}{" "}
                    {conversation.message_count === 1 ? "message" : "messages"}
                  </span>
                  <span className="conversation-date">
                    <Clock size={12} />
                    {formatDate(conversation.updated_at)}
                  </span>
                </div>
              </div>
              <button
                className={`delete-conversation-btn ${
                  isStreaming ? "disabled" : ""
                }`}
                onClick={(e) => {
                  e.stopPropagation();
                  if (!isStreaming) {
                    onDeleteConversation(conversation.conversation_id);
                  }
                }}
                title={isStreaming ? undefined : "Delete conversation"}
                disabled={isStreaming}
              >
                <Trash2 size={16} />
              </button>
            </div>
          ))
        )}
      </div>
      {showTooltip &&
        createPortal(
          <div
            className="streaming-tooltip-follow"
            style={{
              left: `${mousePosition.x}px`,
              top: `${mousePosition.y}px`,
            }}
          >
            {isStreaming
              ? "Navigation is disabled while response is generating."
              : "You have a new conversation open in the main window."}
          </div>,
          document.body
        )}
    </div>
  );
};

export default ConversationList;
