// IMPORTANT NOTE: This and the associated css file were generated by Cursor with a lot of back-and-forth - I have very little
//experience with frontend development, especially using React, so it could help me implement
// things that I was more familiar with in this language.

// also a huge priority for modification
import React from "react";
import { Gauge, ListChecks, Lightbulb } from "lucide-react";
import "./FeedbackPanel.css";

const FeedbackPanel = ({
  qualityScore,
  feedback,
  isTerse,
  loading = false,
}) => {
  const getScoreColor = (score) => {
    if (score === null) return "#6c757d"; // Gray for no score
    if (score >= 8) return "#004600";
    if (score >= 6) return "#fdb515";
    if (score >= 4) return "#f28500";
    return "#dc3545";
  };

  const getScorePercentage = (score) => {
    if (score === null) return 0;
    return (score / 10) * 100;
  };

  // Extract feedback data - handle both old string format and new object format
  const feedbackData = React.useMemo(() => {
    if (!feedback) {
      return {
        quality_label: null,
        word_count: 0,
        improvement_tips: [],
        example_improved_prompt: null,
      };
    }

    // If feedback is a string (old format), return defaults
    if (typeof feedback === "string") {
      return {
        quality_label: null,
        word_count: 0,
        improvement_tips: [],
        example_improved_prompt: null,
      };
    }

    // If feedback is an object (new format), use it directly
    return {
      quality_label: feedback.quality_label || null,
      word_count: feedback.word_count || 0,
      improvement_tips: Array.isArray(feedback.improvement_tips)
        ? feedback.improvement_tips
        : [],
      example_improved_prompt: feedback.example_improved_prompt || null,
    };
  }, [feedback]);

  return (
    <div className="feedback-panel">
      <div className="feedback-header">
        <h2>Prompt Quality Feedback</h2>
      </div>

      <div className="feedback-content">
        {/* Quality Score Section with Horizontal Bar */}
        <div className="score-section">
          <div className="score-section-header">
            <Gauge size={20} />
            <h3>Prompt Score</h3>
          </div>
          {loading ? (
            <div className="quality-bar-container">
              <div className="quality-bar-wrapper">
                <div className="quality-bar-fill loading-bar">
                  <span className="quality-score-overlay">—/10</span>
                </div>
              </div>
              <div className="quality-label">Loading...</div>
            </div>
          ) : qualityScore === null ? (
            <div className="quality-bar-container">
              <div className="quality-bar-wrapper">
                <div className="quality-bar-fill empty-bar"></div>
                <span className="quality-score-overlay empty-score">—/10</span>
              </div>
              <div className="quality-label">—</div>
            </div>
          ) : (
            <div className="quality-bar-container">
              <div className="quality-bar-wrapper">
                <div
                  className="quality-bar-fill"
                  style={{
                    width: `${getScorePercentage(qualityScore)}%`,
                    backgroundColor: getScoreColor(qualityScore),
                  }}
                >
                  <span className="quality-score-overlay">
                    {qualityScore.toFixed(1)}/10
                  </span>
                </div>
              </div>
              <div className="quality-label">
                {feedbackData.quality_label ||
                  (qualityScore >= 8
                    ? "Excellent"
                    : qualityScore >= 6
                    ? "Good"
                    : qualityScore >= 4
                    ? "Fair"
                    : "Poor")}
              </div>
            </div>
          )}
        </div>

        {/* Improvement Tips Section */}
        <div className="improvement-tips-section">
          <div className="improvement-tips-header">
            <ListChecks size={20} />
            <span>Improvement Tips</span>
          </div>
          {loading ? (
            <div className="empty-section-message">
              Analyzing your prompt...
            </div>
          ) : qualityScore === null ? (
            <div className="empty-section-message">
              Send a message to receive personalized improvement tips.
            </div>
          ) : (
            <ul className="improvement-tips-list">
              {feedbackData.improvement_tips.length > 0 ? (
                feedbackData.improvement_tips.map((tip, index) => (
                  <li key={index}>{tip}</li>
                ))
              ) : (
                <>
                  <li>Be more specific in your requests</li>
                  <li>Provide context from previous messages</li>
                  <li>Ask clear, focused questions</li>
                </>
              )}
            </ul>
          )}
        </div>

        {/* Example Improved Prompt Section */}
        <div className="example-prompt-section">
          <div className="example-prompt-header">
            <Lightbulb size={20} />
            <span>Example Improved Prompt</span>
          </div>
          {loading ? (
            <div className="empty-section-message">Generating example...</div>
          ) : qualityScore === null ? (
            <div className="empty-section-message">
              Send a message to see an example of an improved prompt.
            </div>
          ) : feedbackData.example_improved_prompt ? (
            <div className="example-prompt-text">
              {feedbackData.example_improved_prompt}
            </div>
          ) : (
            <div className="empty-section-message">
              No example available for this prompt.
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default FeedbackPanel;
