// IMPORTANT NOTE: This and the associated css file were generated by Cursor with a lot of back-and-forth - I have very little
//experience with frontend development, especially using React, so it could help me implement
// things that I was more familiar with in this language.

import React from "react";
import { Gauge, ListChecks, Lightbulb, Info } from "lucide-react";
import "./FeedbackPanel.css";

const FeedbackPanel = ({ qualityScore, feedback, loading = false }) => {
  const getScoreColor = (score) => {
    if (score === null) return "#6c757d"; // Gray for no score
    if (score >= 8) return "#008500";
    if (score >= 6) return "#fdb515";
    if (score >= 4) return "#f28500";
    return "#dc3545";
  };

  // This is to get the percentage of the score so we can display the bar properly
  const getScorePercentage = (score) => {
    if (score === null) return 0;
    return (score / 10) * 100;
  };

  // Extract feedback data - handle both old string format and new object format
  const feedbackData = React.useMemo(() => {
    if (!feedback) {
      return {
        quality_label: null,
        word_count: 0,
        improvement_tips: [],
        example_improved_prompt: null,
      };
    }

    // If feedback is a string (old format), return defaults
    if (typeof feedback === "string") {
      return {
        quality_label: null,
        word_count: 0,
        improvement_tips: [],
        example_improved_prompt: null,
      };
    }

    // If feedback is an object (new format), use it directly
    return {
      quality_label: feedback.quality_label || null,
      improvement_tips: Array.isArray(feedback.improvement_tips)
        ? feedback.improvement_tips
        : [],
      example_improved_prompt: feedback.example_improved_prompt || null,
    };
  }, [feedback]);

  const [isInfoOpen, setIsInfoOpen] = React.useState(false);

  const openInfo = () => setIsInfoOpen(true);
  const closeInfo = () => setIsInfoOpen(false);

  return (
    <div className="feedback-panel">
      <div className="feedback-header">
        <h2>Prompt Quality Feedback</h2>
        {/* Tutorial modal */}
        <button
          type="button"
          className="feedback-info-button"
          onClick={openInfo}
          aria-label="How prompt scoring works"
        >
          <Info size={18} />
        </button>
      </div>

      <div className="feedback-content">
        {/* Quality Score Section with Horizontal Bar */}
        <div className="score-section">
          <div className="score-section-header">
            <Gauge size={20} />
            <h3>Prompt Score</h3>
          </div>
          {loading ? (
            <div className="quality-bar-container">
              <div className="quality-bar-wrapper">
                <div className="quality-bar-fill loading-bar">
                  <span className="quality-score-overlay">—/10</span>
                </div>
              </div>
              <div className="quality-label">Loading...</div>
            </div>
          ) : qualityScore === null ? (
            <div className="quality-bar-container">
              <div className="quality-bar-wrapper">
                <div className="quality-bar-fill empty-bar"></div>
                <span className="quality-score-overlay empty-score">—/10</span>
              </div>
              <div className="quality-label">—</div>
            </div>
          ) : (
            <div className="quality-bar-container">
              <div className="quality-bar-wrapper">
                <div
                  className="quality-bar-fill"
                  style={{
                    width: `${getScorePercentage(qualityScore)}%`,
                    backgroundColor: getScoreColor(qualityScore),
                  }}
                >
                  <span className="quality-score-overlay">
                    {qualityScore.toFixed(1)}/10
                  </span>
                </div>
              </div>
              <div className="quality-label">
                {feedbackData.quality_label ||
                  (qualityScore >= 8
                    ? "Excellent"
                    : qualityScore >= 6
                    ? "Good"
                    : qualityScore >= 4
                    ? "Fair"
                    : "Poor")}
              </div>
            </div>
          )}
        </div>

        {/* Improvement Tips Section */}
        <div className="improvement-tips-section">
          <div className="improvement-tips-header">
            <ListChecks size={20} />
            <span>Improvement Tips</span>
          </div>
          {loading ? (
            <div className="empty-section-message">
              Analyzing your prompt...
            </div>
          ) : qualityScore === null ? (
            <div className="empty-section-message">
              Send a message to receive personalized improvement tips.
            </div>
          ) : (
            <ul className="improvement-tips-list">
              {feedbackData.improvement_tips.length > 0 ? (
                feedbackData.improvement_tips.map((tip, index) => (
                  <li key={index}>{tip}</li>
                ))
              ) : (
                <>
                  <li>Be more specific in your requests</li>
                  <li>Provide context from previous messages</li>
                  <li>Ask clear, focused questions</li>
                </>
              )}
            </ul>
          )}
        </div>

        {/* Example Improved Prompt Section */}
        <div className="example-prompt-section">
          <div className="example-prompt-header">
            <Lightbulb size={20} />
            <span>Example Improved Prompt</span>
          </div>
          {loading ? (
            <div className="empty-section-message">Generating example...</div>
          ) : qualityScore === null ? (
            <div className="empty-section-message">
              Send a message to see an example of an improved prompt.
            </div>
          ) : feedbackData.example_improved_prompt ? (
            <div className="example-prompt-text">
              {feedbackData.example_improved_prompt}
            </div>
          ) : (
            <div className="empty-section-message">
              No example available for this prompt.
            </div>
          )}
        </div>
      </div>

      {/* Information about prompt scoring */}
      {isInfoOpen && (
        <div className="feedback-info-backdrop" onClick={closeInfo}>
          <div
            className="feedback-info-modal"
            onClick={(e) => e.stopPropagation()}
          >
            <button
              type="button"
              className="feedback-info-close"
              onClick={closeInfo}
              aria-label="Close prompt scoring information"
            >
              ×
            </button>
            <h3>How prompt scoring works</h3>
            <p>prompt.ly scores your prompt using 4 criteria:</p>
            <ul className="feedback-info-list">
              <li>
                <strong>Specificity</strong> – How specific and detailed is your
                request?
                <br />
                <span className="feedback-info-good">
                  Good: &quot;Summarize the key findings around copyright
                  infringement from the research paper I shared about AI ethics,
                  with quotes.&quot;
                </span>
                <br />
                <span className="feedback-info-bad">
                  Bad: &quot;Summarize this.&quot;
                </span>
              </li>
              <li>
                <strong>Critical Thinking</strong> – Does your prompt involve
                analysis or reasoning, instead of just asking for a direct,
                copy-and-paste answer?
                <br />
                <span className="feedback-info-good">
                  Good: &quot;Based on our discussion about machine learning,
                  compare how neural networks and decision trees differ in terms
                  of interpretability for medical diagnosis.&quot;
                </span>
                <br />
                <span className="feedback-info-bad">
                  Bad: &quot;Do this assignment for me.&quot;
                </span>
              </li>
              <li>
                <strong>Conceptual Understanding</strong> – Do you show that you
                understand the topic you&apos;re asking about?
                <br />
                <span className="feedback-info-good">
                  Good: &quot;I&apos;m building a logistic regression model for
                  rare events. Can you help me interpret the coefficients and
                  odds ratios correctly?&quot;
                </span>
                <br />
                <span className="feedback-info-bad">
                  Bad: &quot;Explain this math thing for me&quot; (with no
                  terminology or context).
                </span>
              </li>
              <li>
                <strong>Self-Direction</strong> – Are you working with the AI,
                instead of asking it to do everything for you?
                <br />
                <span className="feedback-info-good">
                  Good: &quot;I&apos;ll draft the introduction based on my
                  notes. Can you suggest 3 ways to tighten the methods section
                  and flag any missing details?&quot;
                </span>
                <br />
                <span className="feedback-info-bad">
                  Bad: &quot;Write my entire project report for me.&quot;
                </span>
              </li>
            </ul>
          </div>
        </div>
      )}
    </div>
  );
};

export default FeedbackPanel;
