// IMPORTANT NOTE: This and the associated css file were generated by Cursor with a lot of back-and-forth - I have very little
// experience with frontend development, especially using React, so it could help me implement
// things that I was more familiar with in this language.
import React from "react";
import { useAuth0 } from "@auth0/auth0-react";
import "./LoginPage.css";
import logo from "../assets/promptly_logo.png";

const LoginPage = () => {
  const { loginWithRedirect } = useAuth0();

  const handleLogin = () => {
    loginWithRedirect();
  };

  return (
    <div className="login-container">
      <div className="login-card">
        <div className="login-header">
          <img src={logo} alt="Prompt.ly" className="login-logo" />
          <h1>Welcome to prompt.ly</h1>
          <p>Prompt better, think better.</p>
        </div>
        <div className="login-content">
          <button className="login-button" onClick={handleLogin}>
            <div className="button-content">
              <svg
                className="auth-icon"
                viewBox="0 0 24 24"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M12 2C6.48 2 2 6.48 2 12C2 17.52 6.48 22 12 22C17.52 22 22 17.52 22 12C22 6.48 17.52 2 12 2ZM12 5C13.66 5 15 6.34 15 8C15 9.66 13.66 11 12 11C10.34 11 9 9.66 9 8C9 6.34 10.34 5 12 5ZM12 19.2C9.5 19.2 7.29 17.92 6 15.98C6.03 13.99 10 12.9 12 12.9C13.99 12.9 17.97 13.99 18 15.98C16.71 17.92 14.5 19.2 12 19.2Z"
                  fill="currentColor"
                />
              </svg>
              <span className="button-text">Sign In</span>
            </div>
          </button>
        </div>
      </div>
    </div>
  );
};

export default LoginPage;
