// IMPORTANT NOTE: This and the associated css file were generated by Cursor with a lot of back-and-forth - I have very little
//experience with frontend development, especially using React, so it could help me implement
//things that I was more familiar with in this language.
import React from "react";
import "./MobileWarning.css";
import logo from "../assets/promptly_logo.png";
// made this so that people don't have a really weird display on the phone (because of the horizontal sections not porting over well to the phone)
const MobileWarning = () => {
  return (
    <div className="mobile-warning-container">
      <div className="mobile-warning-card">
        <div className="mobile-warning-header">
          <img src={logo} alt="Prompt.ly" className="mobile-warning-logo" />
          <h1>prompt.ly</h1>
        </div>
        <div className="mobile-warning-content">
          <p>prompt.ly is best displayed on a computer with a wide window.</p>
        </div>
      </div>
    </div>
  );
};

export default MobileWarning;
