/* IMPORTANT NOTE: This was generated by Cursor with a lot of back-and-forth - I have very little 
experience with frontend development, especially using React, so it could help me implement
things that I was more familiar with in this language. */
import React, { useState } from "react";
import { useAuth0 } from "@auth0/auth0-react";
import { LogOut, User } from "lucide-react";
import "./UserHeader.css";

const UserHeader = () => {
  const { user, logout } = useAuth0();
  const [imageError, setImageError] = useState(false);

  if (!user) return null;

  const handleLogout = () => {
    logout({ logoutParams: { returnTo: window.location.origin } });
  };

  const handleImageError = () => {
    setImageError(true);
  };

  const showImage = user.picture && !imageError;

  return (
    <div className="user-header">
      <div className="user-info">
        {showImage ? (
          <img
            src={user.picture}
            alt={user.name}
            className="user-avatar"
            crossOrigin="anonymous"
            referrerPolicy="no-referrer"
            onError={handleImageError}
          />
        ) : (
          <div className="user-avatar-placeholder">
            <User size={20} />
          </div>
        )}
        <div className="user-details">
          <span className="user-name">{user.name}</span>
          <span className="user-email">{user.email}</span>
        </div>
      </div>
      <button className="logout-button" onClick={handleLogout} title="Logout">
        <LogOut size={18} />
      </button>
    </div>
  );
};

export default UserHeader;
