# IMPORTANT NOTE: This was generated by Cursor to test the database functions.
"""
Unit tests for database.py
Tests database operations: create_user, create_conversation, get_conversation, update_conversation
"""
import pytest
import json
from database import Database

class TestDatabase:
    """Test database operations"""
    
    def test_create_user(self, test_db, sample_user_email):
        """Test creating a new user"""
        result = test_db.create_user(sample_user_email)
        assert result is True
        
        # Verify user exists
        user = test_db.get_user_by_email(sample_user_email)
        assert user is not None
        assert user['email'] == sample_user_email
    
    def test_create_user_duplicate(self, test_db, sample_user_email):
        """Test creating duplicate user (should be idempotent)"""
        test_db.create_user(sample_user_email)
        result = test_db.create_user(sample_user_email)  # Try again
        assert result is True  # Should succeed (idempotent)
    
    def test_get_user_by_email_not_found(self, test_db):
        """Test getting non-existent user"""
        user = test_db.get_user_by_email("nonexistent@example.com")
        assert user is None
    
    def test_create_conversation(self, test_db, sample_user_email, sample_conversation_id):
        """Test creating a new conversation"""
        # Create user first
        test_db.create_user(sample_user_email)
        
        # Create conversation
        result = test_db.create_conversation(sample_user_email, sample_conversation_id)
        assert result is True
        
        # Verify conversation exists
        conversation = test_db.get_conversation(sample_conversation_id)
        assert conversation is not None
        assert conversation['conversation_id'] == sample_conversation_id
        assert conversation['user_email'] == sample_user_email
    
    def test_get_conversation_not_found(self, test_db):
        """Test getting non-existent conversation"""
        conversation = test_db.get_conversation("nonexistent-id")
        assert conversation is None
    
    def test_update_conversation(self, test_db, sample_user_email, sample_conversation_id, sample_messages):
        """Test updating conversation with messages and scores"""
        # Setup: create user and conversation
        test_db.create_user(sample_user_email)
        test_db.create_conversation(sample_user_email, sample_conversation_id)
        
        # Update conversation
        quality_score = 7.5
        message_scores = [7.5]
        feedback = "Good prompt!"
        
        test_db.update_conversation(
            sample_conversation_id,
            sample_messages,
            quality_score,
            message_scores,
            feedback
        )
        
        # Verify update
        conversation = test_db.get_conversation(sample_conversation_id)
        assert conversation is not None
        assert conversation['quality_score'] == quality_score
        assert conversation['feedback'] == feedback
        # message_scores is already parsed from JSON, so use it directly
        assert len(conversation['message_scores']) == 1
    
    def test_get_user_conversations(self, test_db, sample_user_email):
        """Test getting all conversations for a user"""
        # Create user and conversations
        test_db.create_user(sample_user_email)
        test_db.create_conversation(sample_user_email, "conv-1")
        test_db.create_conversation(sample_user_email, "conv-2")
        
        # Get conversations
        conv_ids = test_db.get_user_conversations(sample_user_email)
        assert len(conv_ids) == 2
        assert "conv-1" in conv_ids
        assert "conv-2" in conv_ids
    
    def test_get_conversation_summary(self, test_db, sample_user_email, sample_conversation_id):
        """Test getting conversation summary via get_user_conversation_summaries"""
        # Setup
        test_db.create_user(sample_user_email)
        test_db.create_conversation(sample_user_email, sample_conversation_id)
        
        # Get summaries and find the one we want
        summaries = test_db.get_user_conversation_summaries(sample_user_email)
        summary = next((s for s in summaries if s['conversation_id'] == sample_conversation_id), None)
        assert summary is not None
        assert 'conversation_id' in summary
        assert 'updated_at' in summary
    
    def test_delete_conversation(self, test_db, sample_user_email, sample_conversation_id):
        """Test deleting a conversation"""
        # Setup: create user and conversation
        test_db.create_user(sample_user_email)
        test_db.create_conversation(sample_user_email, sample_conversation_id)
        
        # Verify conversation exists
        conversation = test_db.get_conversation(sample_conversation_id)
        assert conversation is not None
        
        # Delete conversation
        result = test_db.delete_conversation(sample_conversation_id, sample_user_email)
        assert result is True
        
        # Verify conversation is deleted
        conversation = test_db.get_conversation(sample_conversation_id)
        assert conversation is None
    
    def test_delete_conversation_wrong_user(self, test_db, sample_user_email, sample_conversation_id):
        """Test deleting a conversation belonging to another user fails"""
        # Setup: create user and conversation
        test_db.create_user(sample_user_email)
        test_db.create_conversation(sample_user_email, sample_conversation_id)
        
        # Try to delete with different user email
        result = test_db.delete_conversation(sample_conversation_id, "other@example.com")
        assert result is False
        
        # Verify conversation still exists
        conversation = test_db.get_conversation(sample_conversation_id)
        assert conversation is not None
    
    def test_delete_conversation_not_found(self, test_db, sample_user_email):
        """Test deleting non-existent conversation"""
        test_db.create_user(sample_user_email)
        result = test_db.delete_conversation("nonexistent-id", sample_user_email)
        assert result is False
    
    def test_get_user_conversation_summaries(self, test_db, sample_user_email):
        """Test getting conversation summaries for a user"""
        # Setup: create user and multiple conversations
        test_db.create_user(sample_user_email)
        test_db.create_conversation(sample_user_email, "conv-1")
        test_db.create_conversation(sample_user_email, "conv-2")
        test_db.create_conversation(sample_user_email, "conv-3")
        
        # Add messages to one conversation
        messages = [
            {"role": "user", "content": "Hello", "timestamp": "2024-01-01T00:00:00"},
            {"role": "assistant", "content": "Hi there", "timestamp": "2024-01-01T00:00:01"}
        ]
        test_db.update_conversation("conv-1", messages, 7.5, [7.5], "Good prompt", "Test Title")
        
        # Get summaries
        summaries = test_db.get_user_conversation_summaries(sample_user_email)
        
        assert len(summaries) == 3
        assert all('conversation_id' in s for s in summaries)
        assert all('title' in s for s in summaries)
        assert all('updated_at' in s for s in summaries)
        assert all('message_count' in s for s in summaries)
        
        # Find conv-1 and verify message_count
        conv1 = next(s for s in summaries if s['conversation_id'] == 'conv-1')
        assert conv1['message_count'] == 2
        assert conv1['title'] == "Test Title"
    
    def test_get_user_conversation_summaries_with_limit(self, test_db, sample_user_email):
        """Test getting conversation summaries with limit"""
        test_db.create_user(sample_user_email)
        for i in range(5):
            test_db.create_conversation(sample_user_email, f"conv-{i}")
        
        summaries = test_db.get_user_conversation_summaries(sample_user_email, limit=3)
        assert len(summaries) == 3
    
    def test_get_user_conversation_summaries_with_offset(self, test_db, sample_user_email):
        """Test getting conversation summaries with offset"""
        test_db.create_user(sample_user_email)
        for i in range(5):
            test_db.create_conversation(sample_user_email, f"conv-{i}")
        
        summaries = test_db.get_user_conversation_summaries(sample_user_email, limit=2, offset=2)
        assert len(summaries) == 2
    
    def test_get_conversation_with_limit_messages(self, test_db, sample_user_email, sample_conversation_id):
        """Test getting conversation with message limit"""
        test_db.create_user(sample_user_email)
        test_db.create_conversation(sample_user_email, sample_conversation_id)
        
        # Add many messages
        messages = []
        for i in range(10):
            messages.append({"role": "user", "content": f"Message {i}", "timestamp": f"2024-01-01T00:00:{i:02d}"})
            messages.append({"role": "assistant", "content": f"Response {i}", "timestamp": f"2024-01-01T00:00:{i+1:02d}"})
        
        test_db.update_conversation(sample_conversation_id, messages, 7.5, [7.5] * 10, "Feedback")
        
        # Get conversation with limit
        conversation = test_db.get_conversation(sample_conversation_id, limit_messages=4)
        assert conversation is not None
        assert len(conversation['messages']) == 4
        assert conversation['has_more_messages'] is True
        assert conversation['total_message_count'] == 20
    
    def test_update_user_profile(self, test_db, sample_user_email):
        """Test updating user profile"""
        test_db.create_user(sample_user_email)
        
        result = test_db.update_user_profile(
            sample_user_email,
            first_name="Updated",
            last_name="Name",
            google_id="google-123",
            profile_picture_url="https://example.com/pic.jpg"
        )
        assert result is True
        
        user = test_db.get_user_by_email(sample_user_email)
        assert user['first_name'] == "Updated"
        assert user['last_name'] == "Name"
        assert user['google_id'] == "google-123"
        assert user['profile_picture_url'] == "https://example.com/pic.jpg"
    
    def test_update_user_login(self, test_db, sample_user_email):
        """Test updating user last login timestamp"""
        test_db.create_user(sample_user_email)
        
        user_before = test_db.get_user_by_email(sample_user_email)
        initial_login = user_before['last_login']
        
        import time
        time.sleep(0.1)  # Small delay to ensure timestamp difference
        
        # Call update_user_login - should not raise an error
        test_db.update_user_login(sample_user_email)
        
        user_after = test_db.get_user_by_email(sample_user_email)
        # Check that last_login exists and update_user_login completed successfully
        assert user_after is not None
        assert user_after['last_login'] is not None
        # For SQLite, timestamps might be identical if the update happens in the same second
        # The important thing is that the function was called without error
        # In a real scenario with more time between calls, the timestamp would be different
    
    def test_update_conversation_with_title(self, test_db, sample_user_email, sample_conversation_id, sample_messages):
        """Test updating conversation with title"""
        test_db.create_user(sample_user_email)
        test_db.create_conversation(sample_user_email, sample_conversation_id)
        
        test_db.update_conversation(
            sample_conversation_id,
            sample_messages,
            7.5,
            [7.5],
            "Good prompt!",
            title="My Conversation"
        )
        
        conversation = test_db.get_conversation(sample_conversation_id)
        assert conversation['title'] == "My Conversation"
    
    def test_update_conversation_message_count(self, test_db, sample_user_email, sample_conversation_id):
        """Test that message_count is updated correctly"""
        test_db.create_user(sample_user_email)
        test_db.create_conversation(sample_user_email, sample_conversation_id)
        
        messages = [
            {"role": "user", "content": "Hello"},
            {"role": "assistant", "content": "Hi"},
            {"role": "user", "content": "How are you?"}
        ]
        
        test_db.update_conversation(sample_conversation_id, messages, 7.5, [7.5, 8.0], "Feedback")
        
        summaries = test_db.get_user_conversation_summaries(sample_user_email)
        conv = next(s for s in summaries if s['conversation_id'] == sample_conversation_id)
        assert conv['message_count'] == 3

