/* IMPORTANT NOTE: This was generated by Cursor to connect the frontend to the backend functions. */
import axios from "axios";

const API_BASE_URL =
  process.env.REACT_APP_API_URL || "http://localhost:5001/api";

// Log API URL in production to help debug (only in browser console)
if (process.env.NODE_ENV === "production") {
  console.log("API Base URL:", API_BASE_URL);
}

// Create API service factory that accepts token getter
// sets a base url and adds a header to all the requests
export const createApiService = (getAccessTokenSilently) => {
  const api = axios.create({
    baseURL: API_BASE_URL,
    headers: {
      "Content-Type": "application/json",
    },
    timeout: 60000, // 60 second timeout for API calls
  });

  //  intercepts all requests to include auth token
  api.interceptors.request.use(
    async (config) => {
      try {
        const token = await getAccessTokenSilently();
        if (token) {
          config.headers.Authorization = `Bearer ${token}`;
        }
      } catch (error) {
        console.error("Error getting token:", error);
        // Don't block the request, but log the error
      }
      return config;
    },
    (error) => {
      console.error("Request interceptor error:", error);
      return Promise.reject(error);
    }
  );

  // Add response interceptor to log errors
  api.interceptors.response.use(
    (response) => response,
    (error) => {
      if (error.code === "ECONNABORTED") {
        console.error("Request timeout - backend may be slow or unreachable");
      } else if (error.message === "Network Error") {
        console.error("Network Error - Check REACT_APP_API_URL:", API_BASE_URL);
        console.error(
          "Is backend running? Try:",
          API_BASE_URL.replace("/api", "/api/health")
        );
      } else if (error.response) {
        console.error(
          "API Error Response:",
          error.response.status,
          error.response.data
        );
      } else {
        console.error("API Error:", error.message);
      }
      return Promise.reject(error);
    }
  );

  return {
    // Get all conversations (with optional pagination that i didnt end up implementing)
    getConversations: async (limit = null, offset = 0) => {
      const params = {};
      if (limit !== null) {
        params.limit = limit;
        params.offset = offset;
      }
      const response = await api.get("/conversations", { params });
      return response.data;
    },

    // Get a specific conversation (with optional message limit for faster loading)
    // By default, loads all messages since conversations are capped at 20 user messages
    getConversation: async (conversationId, limitMessages = null) => {
      const params = {};
      if (limitMessages !== null) {
        params.limit_messages = limitMessages;
      }
      const response = await api.get(`/conversations/${conversationId}`, {
        params,
      });
      return response.data;
    },

    // Delete a conversation
    deleteConversation: async (conversationId) => {
      const response = await api.delete(`/conversations/${conversationId}`);
      return response.data;
    },

    // Send a message to a conversation (with optional file attachments, up to 3)
    sendMessage: async (
      conversationId,
      message,
      fileAttachments = null,
      signal = null
    ) => {
      const payload = {
        message: message,
      };

      // Add file attachments if provided (array of up to 3 files)
      if (
        fileAttachments &&
        Array.isArray(fileAttachments) &&
        fileAttachments.length > 0
      ) {
        payload.file_attachments = fileAttachments;
      }

      const response = await api.post(
        `/conversations/${conversationId}/messages`,
        payload,
        { signal: signal } // Add AbortController signal in case the user deletes the conversation
      );
      return response.data;
    },

    getAIResponse: async (
      conversationId,
      onChunk,
      onComplete,
      onError,
      signal = null
    ) => {
      // Streaming version using fetch for Server-Sent Events
      try {
        const token = await getAccessTokenSilently();
        const response = await fetch(
          `${API_BASE_URL}/conversations/${conversationId}/response`,
          {
            method: "POST",
            headers: {
              Authorization: `Bearer ${token}`,
              "Content-Type": "application/json",
            },
            signal: signal, // Add AbortController signal
          }
        );

        if (!response.ok) {
          const errorData = await response
            .json()
            .catch(() => ({ error: "Unknown error" }));
          throw new Error(
            errorData.error || `HTTP error! status: ${response.status}`
          );
        }

        const reader = response.body.getReader();
        const decoder = new TextDecoder();
        let buffer = "";

        // reads the chunks of the response - the streaming that I wanted to implement
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;

          buffer += decoder.decode(value, { stream: true });
          const lines = buffer.split("\n");
          buffer = lines.pop() || ""; // Keep incomplete line in buffer

          for (const line of lines) {
            if (line.startsWith("data: ")) {
              try {
                const data = JSON.parse(line.slice(6)); // Remove 'data: ' prefix

                if (data.error) {
                  onError(data);
                  return;
                }

                if (data.chunk && onChunk) {
                  // Call onChunk immediately for each chunk
                  onChunk(data.chunk);
                }

                if (data.done && onComplete) {
                  onComplete(data.full_response);
                  return;
                }
              } catch (e) {
                console.error("Error parsing SSE data:", e, line);
              }
            }
          }
        }
      } catch (error) {
        // Handle abort gracefully - don't show error for user-initiated aborts
        if (error.name === "AbortError" || signal?.aborted) {
          console.log("Stream aborted");
          // Silently stop - don't call onError for aborts
          return;
        }
        console.error("Streaming error:", error);
        if (onError) {
          onError({ error: error.message });
        } else {
          throw error;
        }
      }
    },

    // Health check
    healthCheck: async () => {
      const response = await api.get("/health");
      return response.data;
    },
  };
};
